name: Build and test application
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      id: login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image
      id: build
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/flashapp-helloworld
    - name: Push docker image
      id: push
      run: docker push ${{ secrets.DOCKER_USER }}/flashapp-helloworld